<x-layout>
    <form action="{{ route('products.store') }}" method="POST">


        {{-- CSRF Token --}}
        {{-- This is a security feature in Laravel to prevent CSRF attacks --}}
        {{-- It generates a hidden input field with a token that is checked on form submission --}}
        {{-- The token is automatically generated by the csrf_field() helper function --}}
        {{-- This is important for form submissions in Laravel --}}
        @csrf
        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12">
                <h2 class="text-base/7 font-semibold text-gray-900">Create a New Product</h2>
                {{-- VALIDATION ERRORS --}}
                @if ($errors->any())
                    <div class="mt-4 bg-red-50 border-l-4 border-red-400 text-red-700 rounded-md">
                        <p>Please fix the following errors:</p>
                        <ul class="list-disc list-inside text-sm">
                            {{-- Loop through each error and display it --}}
                            @foreach ($errors->all() as $error)
                                <li class="my-2 text-red-500 pl-5">{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-2 sm:grid-cols-6">
                    <div class="col-span-full">
                        <label for="name" class="block text-sm/6 font-medium text-gray-900">Product Name</label>
                        <div class="mt-2">
                            <input type="name" name="name" id="name" autocomplete="name"
                                value="{{ old('name') }}" required
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>

                    <div class="col-span-full">
                        <label for="product-description" class="block text-sm/6 font-medium text-gray-900">Product
                            Description</label>
                        <div class="mt-2">
                            <textarea name="description" id="product-description" rows="3" required
                                placeholder="Write a few sentences about the product."
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">{{ old('description') }}</textarea>
                        </div>
                    </div>
                    <div class="sm:col-span-2 sm:col-start-1">
                        <label for="product-price" class="block text-sm/6 font-medium text-gray-900"> Price</label>
                        <div class="mt-2">
                            <input type="number" name="price" id="product-price" autocomplete="product-price"
                                min="0" value="{{ old('price') }}" required
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>

                    <div class="sm:col-span-2">
                        <label for="product-sku" class="block text-sm/6 font-medium text-gray-900"> SKU</label>
                        <div class="mt-2">
                            <input type="text" name="sku" id="product-sku" autocomplete="product-sku"
                                value="{{ old('sku') }}" required
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>

                    <div class="sm:col-span-2">
                        <label for="product-stock" class="block text-sm/6 font-medium text-gray-900"> Stock</label>
                        <div class="mt-2">
                            <input type="number" name="stock" id="product-stock" autocomplete="product-stock"
                                min="0" value="{{ old('stock') }}" required
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>
                    <div class="col-span-full">
                        <label for="product-category" class="block text-sm/6 font-medium text-gray-900">Product
                            Category</label>
                        <div class="mt-2">
                            <input type="name" name="category" id="product-category" autocomplete="product-category"
                                value="{{ old('category') }}" required
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                        </div>
                    </div>

                    <div class="col-span-full">
                        <label for="cover-photo" class="block text-sm/6 font-medium text-gray-900">Image</label>
                        <div
                            class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
                            <div class="text-center">
                                <svg class="mx-auto size-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor"
                                    aria-hidden="true" data-slot="icon">
                                    <path fill-rule="evenodd"
                                        d="M1.5 6a2.25 2.25 0 0 1 2.25-2.25h16.5A2.25 2.25 0 0 1 22.5 6v12a2.25 2.25 0 0 1-2.25 2.25H3.75A2.25 2.25 0 0 1 1.5 18V6ZM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0 0 21 18v-1.94l-2.69-2.689a1.5 1.5 0 0 0-2.12 0l-.88.879.97.97a.75.75 0 1 1-1.06 1.06l-5.16-5.159a1.5 1.5 0 0 0-2.12 0L3 16.061Zm10.125-7.81a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Z"
                                        clip-rule="evenodd" />
                                </svg>
                                <div class="mt-4 flex text-sm/6 text-gray-600">
                                    <label for="file-upload"
                                        class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 focus-within:outline-hidden hover:text-indigo-500">
                                        <span>Upload a file</span>
                                        <input id="file-upload" name="file-upload" type="file" class="sr-only">
                                    </label>
                                    <p class="pl-1">or drag and drop</p>
                                </div>
                                <p class="text-xs/5 text-gray-600">PNG, JPG, GIF up to 10MB</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-span-full">
                        <label for="product-feature-id"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> Feature:</label>
                        <select id="product-feature-id" name="feature_id" required
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            <option selected disabled>Select a Feature</option>
                            @foreach ($features as $feature)
                                <option value="{{ $feature->id }}"
                                    {{ $feature->id == old('feature_id') ? 'selected' : '' }}>{{ $feature->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="sm:col-start-1 flex items-center ps-4 ">
                        <input type="checkbox" id="product-active" name="is_active" value="1"
                            {{ old('is_active') ? 'checked' : '' }}
                            class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="product-active"
                            class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Active</label>
                    </div>
                </div>
            </div>




        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
            <button type="button" class="text-sm/6 font-semibold text-gray-900">Cancel</button>
            <button type="submit"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
        </div>


    </form>
</x-layout>
