<x-layout>
    <form action="{{ route('products.update', $product->id) }}" method="POST" enctype="multipart/form-data">


        {{-- CSRF Token --}}
        {{-- This is a security feature in Laravel to prevent CSRF attacks --}}
        {{-- It generates a hidden input field with a token that is checked on form submission --}}
        {{-- The token is automatically generated by the csrf_field() helper function --}}
        {{-- This is important for form submissions in Laravel --}}
        @csrf
        @method('PUT')

        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12">
                <h2 class="text-base/7 font-semibold text-gray-900">Update {{ $product->name }}</h2>
                {{-- VALIDATION ERRORS --}}
                @if ($errors->any())
                    <div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"
                        role="alert">
                        <svg class="shrink-0 inline w-4 h-4 me-3 mt-[2px]" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                            <path
                                d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z" />
                        </svg>
                        <span class="sr-only">Danger</span>
                        <div>
                            <span class="font-medium">Ensure that requirements are met.</span>
                        </div>
                    </div>
                @endif
                <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-2 sm:grid-cols-6">
                    <div class="col-span-full">
                        <label for="name" class="block text-sm/6 font-medium text-gray-900">Product Name</label>
                        <div class="mt-2">
                            <input type="name" name="name" id="name" autocomplete="name"
                                value="{{ $product->name }}" required autofocus
                                class="border text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 
                                @error('name') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror">
                        </div>
                        @error('name')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>

                    <div class="col-span-full">
                        <label for="product-description" class="block text-sm/6 font-medium text-gray-900">Product
                            Description</label>
                        <div class="mt-2">
                            <textarea name="description" id="product-description" rows="3" required
                                placeholder="Write a few sentences about the product."
                                class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">{{ $product->description }}</textarea>
                        </div>

                        @error('description')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>
                    <div class="sm:col-span-2 sm:col-start-1">
                        <label for="product-price" class="block text-sm/6 font-medium text-gray-900"> Price</label>
                        <div class="mt-2">
                            <input type="number" name="price" id="product-price" autocomplete="product-price"
                                min="0" value="{{ $product->price }}" required
                                class="border text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 
                                @error('price') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror">
                        </div>
                        @error('price')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>

                    <div class="sm:col-span-2">
                        <label for="product-sku" class="block text-sm/6 font-medium text-gray-900"> SKU</label>
                        <div class="mt-2">
                            <input type="text" name="sku" id="product-sku" autocomplete="product-sku"
                                value="{{ $product->sku }}" required
                                @error('sku') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror">
                        </div>
                        @error('sku')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>

                    <div class="sm:col-span-2">
                        <label for="product-stock" class="block text-sm/6 font-medium text-gray-900"> Stock</label>
                        <div class="mt-2">
                            <input type="number" name="stock" id="product-stock" autocomplete="product-stock"
                                min="0" value="{{ $product->stock }}" required
                                @error('stock') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror">
                        </div>
                        @error('stock')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>
                    <div class="col-span-full">
                        <label for="product-category" class="block text-sm/6 font-medium text-gray-900">Product
                            Category</label>
                        <div class="mt-2">
                            <input type="name" name="category" id="product-category" autocomplete="product-category"
                                value="{{ $product->category }}" required
                                @error('category') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror">
                        </div>
                        @error('category')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>

                    <div class="col-span-full mb-2">
                        <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                            for="product-image">Upload Product Image (PNG, JPG, GIF up to 10MB)</label>
                        <input
                            class="border text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 
                                @error('image') border-red-500 bg-red-50 text-red-900 @else border-gray-300 bg-white text-gray-900 @enderror"
                            name="image" id="product-image" type="file">
                        @error('image')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror

                        <img class="h-auto max-w-lg rounded-lg mt-2" src="{{ $image }}" id="imagePreview"
                            alt="{{ $product->name }}">

                    </div>


                    <div class="col-span-full">
                        <label for="product-feature-id"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"> Feature:</label>
                        <select id="product-feature-id" name="feature_id" required
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            <option selected disabled>Select a Feature</option>
                            @foreach ($features as $feature)
                                <option value="{{ $feature->id }}"
                                    {{ $feature->id == $product->feature_id ? 'selected' : '' }}>{{ $feature->name }}
                                </option>
                            @endforeach
                        </select>

                        @error('feature_id')
                            <p class="mt-2 text-xs text-red-600 dark:text-red-500"><span
                                    class="font-medium">{{ $message }}</span></p>
                        @enderror
                    </div>
                    <div class="sm:col-start-1 flex items-center ps-4 ">
                        <input type="checkbox" id="product-active" name="is_active" value="1"
                            {{ $product->is_active ? 'checked' : '' }}
                            class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <label for="product-active"
                            class="w-full py-4 ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Active</label>
                    </div>
                </div>
            </div>




        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ route('products.show', $product->id) }}"
                class="text-sm/6 font-semibold text-gray-900">Cancel</a>
            <button type="submit"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Update</button>
        </div>


    </form>
</x-layout>
